/**
 * L1 本地意图路由种子样本（每类 ~20 条，覆盖规则未命中的自然语言措辞）。
 * 纯数据文件：L1 分类器启动时用它们离线训练（TF-IDF + 质心，<100ms），
 * 后续可用 .local/local-router/train.jsonl 追加真实样本（每行 {"text","mode"}）。
 */
export const LOCAL_ROUTER_SEED: Array<{ text: string; mode: string }> = [
  // ── discuss：讨论 / 剧情 / 设定优化 ──
  { text: '聊聊剧情', mode: 'discuss' },
  { text: '我们讨论一下这个设定', mode: 'discuss' },
  { text: '主角的金手指这样设计合理吗', mode: 'discuss' },
  { text: '我有个新点子，帮我分析下', mode: 'discuss' },
  { text: '说说看这个世界观有没有硬伤', mode: 'discuss' },
  { text: '帮我把势力关系理一理', mode: 'discuss' },
  { text: '讨论一下第一卷的大纲方向', mode: 'discuss' },
  { text: '这个配角的动机要不要改', mode: 'discuss' },
  { text: '主角性格是不是太单薄了', mode: 'discuss' },
  { text: '分析一下这个开篇的卖点', mode: 'discuss' },
  { text: '我在纠结两个题材方向，给点意见', mode: 'discuss' },
  { text: '讨论一下书名怎么起', mode: 'discuss' },
  { text: '这段剧情的逻辑通不通', mode: 'discuss' },
  { text: '帮我对比一下两个金手指方案', mode: 'discuss' },
  { text: '聊聊主角的成长线怎么安排', mode: 'discuss' },
  { text: '设定里的力量体系要不要调整', mode: 'discuss' },
  { text: '探讨一下反派怎么塑造', mode: 'discuss' },
  { text: '大纲第二卷这样写会不会太平', mode: 'discuss' },
  { text: '给我的设定提提意见', mode: 'discuss' },
  { text: '先不写，我们先讨论思路', mode: 'discuss' },
  { text: '女主角的感情线怎么铺比较好', mode: 'discuss' },

  // ── write：写正文 / 日更 / 续写 / 细纲 ──
  { text: '写第12章', mode: 'write' },
  { text: '继续写下一章', mode: 'write' },
  { text: '日更三章', mode: 'write' },
  { text: '帮我把第 108 章的稿子写出来', mode: 'write' },
  { text: '续写正文', mode: 'write' },
  { text: '开新书，先出卷纲和细纲', mode: 'write' },
  { text: '写个短篇试试', mode: 'write' },
  { text: '按细纲把这一章写完', mode: 'write' },
  { text: '把第13章写出来', mode: 'write' },
  { text: '今天的更新章节写一下', mode: 'write' },
  { text: '码两章存稿', mode: 'write' },
  { text: '接着上回的剧情往下写', mode: 'write' },
  { text: '把这段正文补完整', mode: 'write' },
  { text: '写第一章', mode: 'write' },
  { text: '开书写正文', mode: 'write' },
  { text: '先出这一章的细纲再写正文', mode: 'write' },
  { text: '把第 20 章内容写出来', mode: 'write' },
  { text: '接着写，从主角进城开始', mode: 'write' },
  { text: '帮我写正文，按大纲来', mode: 'write' },
  { text: '更一下今天的文', mode: 'write' },
  { text: '继续写第 12 章，主角进入学院的描写再细一点', mode: 'write' },

  // ── import：导入外部章节 ──
  { text: '导入一章', mode: 'import' },
  { text: '这是我自己在别处写的章节，帮我适配进来', mode: 'import' },
  { text: '我用其他AI写了一章，粘贴给你处理', mode: 'import' },
  { text: '把这段外部内容导入工作区', mode: 'import' },
  { text: '粘贴一段小说正文，帮我格式化入库', mode: 'import' },
  { text: '帮我把这篇文章导入成第5章', mode: 'import' },
  { text: '这是外部草稿，走导入流程', mode: 'import' },
  { text: '我从别的平台搬来一章，适配一下', mode: 'import' },
  { text: '导入模式处理这段文字', mode: 'import' },
  { text: '把我朋友的稿子导入进书里', mode: 'import' },
  { text: '这段是导出的旧稿，导入并补追踪', mode: 'import' },
  { text: '帮我把手写稿导入进来', mode: 'import' },
  { text: '外部章节适配一下', mode: 'import' },
  { text: '我在手机上写了一章，导入进来', mode: 'import' },
  { text: '粘贴进来一章，帮我入库', mode: 'import' },
  { text: '这是我在别的网站写的，导进来', mode: 'import' },

  // ── polish：去AI味 / 润色 / 优化 / 大修 ──
  { text: '去一下AI味', mode: 'polish' },
  { text: '这章AI味太重了，帮我改改', mode: 'polish' },
  { text: '优化第5章的文笔', mode: 'polish' },
  { text: '润色一下这段对话', mode: 'polish' },
  { text: '把第8章大修一遍', mode: 'polish' },
  { text: '重写第3章，节奏太拖了', mode: 'polish' },
  { text: '文笔再打磨一下', mode: 'polish' },
  { text: '这段读着太生硬，优化下', mode: 'polish' },
  { text: '帮我把整章润一遍', mode: 'polish' },
  { text: '去AI味，保留剧情', mode: 'polish' },
  { text: '描写太干了，扩写润色一下', mode: 'polish' },
  { text: '这几段重新组织一下语言', mode: 'polish' },
  { text: '把开头改得更抓人', mode: 'polish' },
  { text: '优化对话，少点翻译腔', mode: 'polish' },
  { text: '大修这一卷', mode: 'polish' },
  { text: '帮我重写开头三章', mode: 'polish' },
  { text: '这段太啰嗦，精简润色', mode: 'polish' },
  { text: '文风再老练一点', mode: 'polish' },
  { text: '这段文字太像AI写的，帮我改改', mode: 'polish' },
  { text: '润一下第14章', mode: 'polish' },

  // ── market：扫榜 / 拆书 / 市场调研 ──
  { text: '当前市场上比较火的都有哪些', mode: 'market' },
  { text: '历史文现在什么行情', mode: 'market' },
  { text: '最近什么题材火', mode: 'market' },
  { text: '扫一下起点月票榜', mode: 'market' },
  { text: '拆解一下这本书', mode: 'market' },
  { text: '番茄畅销榜前十都有啥', mode: 'market' },
  { text: '现在流行什么类型的网文', mode: 'market' },
  { text: '帮我调研都市异能赛道的市场', mode: 'market' },
  { text: '拆一下这本书的黄金三章', mode: 'market' },
  { text: '长篇什么火', mode: 'market' },
  { text: '分析一下免费榜的趋势', mode: 'market' },
  { text: '这本书为什么能火，拆一下', mode: 'market' },
  { text: '扫榜看看女频风向', mode: 'market' },
  { text: '最近爆款有什么共性', mode: 'market' },
  { text: '调研一下付费短篇的口味', mode: 'market' },
  { text: '市场上系统流还吃香吗', mode: 'market' },
  { text: '看看最近榜单有哪些新书', mode: 'market' },
  { text: '帮我分析爆款题材', mode: 'market' },
  { text: '历史文现在怎么样？有没有推荐？', mode: 'market' },
  { text: '历史文最近怎么样', mode: 'market' },
  { text: '现在写历史文怎么样', mode: 'market' },
  { text: '这本书怎么样，值不值得写', mode: 'market' },
  { text: '帮我推荐个能写的题材', mode: 'market' },
  { text: '有什么火的书推荐一下', mode: 'market' },
  { text: '帮我看看这个题材有没有搞头', mode: 'market' },
  { text: '写这个方向有前途吗', mode: 'market' },
  { text: '这个品类现在吃香吗', mode: 'market' },

  // ── review：审稿 / 检查 ──
  { text: '帮我看看最近几章读起来哪里不对劲', mode: 'review' },
  { text: '审一下第7到9章', mode: 'review' },
  { text: '检查这一章有没有逻辑漏洞', mode: 'review' },
  { text: '给这几章做个全面审稿', mode: 'review' },
  { text: '看看新写的这章有什么问题', mode: 'review' },
  { text: '帮我审查伏笔回收情况', mode: 'review' },
  { text: '检查全书前十章的质量', mode: 'review' },
  { text: '帮我看看这段的节奏有没有问题', mode: 'review' },
  { text: '挑挑这一章的毛病', mode: 'review' },
  { text: '用审稿标准看看这章能不能过', mode: 'review' },
  { text: '帮我把关一下这章的对话', mode: 'review' },
  { text: '这几章读起来顺不顺，审一下', mode: 'review' },
  { text: '检查人设有没有崩', mode: 'review' },
  { text: '审一遍第12章', mode: 'review' },
  { text: '全面审稿前五章', mode: 'review' },
  { text: '帮我看看有没有写出戏的地方', mode: 'review' },

  // ── preview：预览 / 听书 / 阅读器（只读，不动 Agent）──
  { text: '预览一下最新章节', mode: 'preview' },
  { text: '切到阅读界面', mode: 'preview' },
  { text: '我要听听书', mode: 'preview' },
  { text: '把第10章放到阅读器里', mode: 'preview' },
  { text: '预览模式打开', mode: 'preview' },
  { text: '听一下这一章', mode: 'preview' },
  { text: '打开资料卡墙看看', mode: 'preview' },
  { text: '切换到预览看看效果', mode: 'preview' },
  { text: '听书从上一章继续', mode: 'preview' },
  { text: '打开追踪面板看看', mode: 'preview' },
  { text: '预览下封面效果', mode: 'preview' },
  { text: '我先自己翻翻正文', mode: 'preview' },
  { text: '听感校对一下对白', mode: 'preview' },
  { text: '打开阅读器', mode: 'preview' },
  { text: '帮我翻到最新一章看看', mode: 'preview' },
]
